#!/bin/bash
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409001_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/410130_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/402205a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409215b_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401012_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401549_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/425007_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401211a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/414207a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409002_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401224a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409017_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409200a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409029_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409008_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/414203c_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/flowtosa_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260500_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409030_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401203a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401027_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/401201a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/407202c_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/lkalbert_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/lkalex_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4261093_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260903_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260902_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260519_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260518_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260517_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260516_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260515_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260514_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260513_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260511_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260510_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260509_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260508_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260506_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260505_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260501_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/405232c_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/meninde_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/414216a_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4261110_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/409026_historical.csv
https://riverdata.mdba.gov.au/sites/default/files/liveriverdata/csv/a4260526_historical.csv
